### ISSUE TITLE
Flutter Web "fastdriver" command not working

### ISSUE THREAD

**Issue by ollikas** [tomaszpolanski/fast_flutter_driver#100]
Hi!

Im building a web application and would like to use fast_flutter_driver for testing.
I wen over the tutorial, added generic classes and fastdriver dependency.

Upon calling `fastdriver -d chrome` im getting puch of errors coming from .pub-cache/hosted/pub.dartlang.org/ffi and win directories stating that virtually nothing in there is found or isnt a type.

**Comment by tomaszpolanski** [comment]
Hey @ollikas ,
currently, I am working on support for the web - if I do not find any more blockers, the support for it will be done pretty soon

**Comment by tomaszpolanski** [comment]
@ollikas I've resolved the issue with using native io on the web.
You can try out again your web tests on `fast_flutter_driver_tool 1.5.0` and `fast_flutter_driver 1.3.0`.

Currently, there are massive changes between flutter `master` and `stable` in `WebDriverService` so fastdriver needs to wait until web driver stabilizes until I can guarantee stable support for testing web.
