### ISSUE TITLE
[Q] Is it possible to use this with an Async app

### ISSUE THREAD

**Issue by RemeJuan** [tomaszpolanski/fast_flutter_driver#101]
Looking at all the docs and testing it out I cannot see a way to get around required a `Widget` to be passed into the `generic` setup, however, I make sue of an Async app, which has quite a bit of bootstrap logic that needs to run before loading the main apps widgets. 

WIthout calling `app.main()`, the app cannot run in the driver side and passing that into the setup does not work.

Thanks.

**Comment by tomaszpolanski** [comment]
Hey @RemeJuan ,
could you elaborate on what on your issue?
What I understand is that in your normal `main` you run some additional logic - is that right?
What do you need to run additionally?

What is the issue with executing that logic inside `generic.dart::main`?

**Comment by RemeJuan** [comment]
Quite a lot actually, as it's an API configurable app everything from localization, theming, dependency injection, sentry tracking, push notifications, etc all get bootstrapped before the app can even load.

The app cannot load until all those dependencies have finished.

```
Future main() async {
  // Enable network logging in debugger
  if (foundation.kDebugMode && !foundation.kIsWeb) {
    HttpClient.enableTimelineLogging = true;
  }

  WidgetsFlutterBinding.ensureInitialized();

  await AppHelpers.init();

  String path;
  AssetLoader assetLoader;

  if (foundation.kIsWeb) {
    path = ApiEndpoint.uri('/locale').toString();
    assetLoader = HttpAssetLoader();
  } else {
    path = await LocaleHelpers.storagePath();
    assetLoader = FileAssetLoader();
  }

  await runZonedGuarded<Future<void>>(
    () async {
      runApp(
        EasyLocalization(
          path: path,
          useOnlyLangCode: true,
          supportedLocales: globals.supportedLocale,
          fallbackLocale: const Locale('en'),
          assetLoader: assetLoader,
          child: Container(
            color: Colors.white,
            child: Stack(
              alignment: Alignment.center,
              children: <Widget>[
                AppIcon(),
                App(),
              ],
            ),
          ),
        ),
      );
    },
    (Object error, StackTrace stackTrace) {
      if (foundation.kReleaseMode) {
        try {
          globals.sentry.captureException(
            exception: error,
            stackTrace: stackTrace,
          );
          debugPrint('Error sent to sentry.io: $error');
        } catch (e) {
          debugPrint('Sending report to sentry.io failed: $e');
          debugPrint('Original error: $error');
        }
      }
    },
  );
}
```

**Comment by tomaszpolanski** [comment]
If you add the setup to `generic.dart` it does not work?
I am aware that you would not be able to reset the setup's configuration like that but first I want to understand where exactly the problem lies.

**Comment by RemeJuan** [comment]
Never considered that, as I have always run into issues when bringing app code into the test, will give that a bash and see how it goes and get back to you.

Thanks for the help so far.

**Comment by tomaszpolanski** [comment]
If the suggestion did not solve the issue, please let me know
