### ISSUE TITLE
How to run specific test group using fastdriver?

### ISSUE THREAD

**Issue by KrishnB** [tomaszpolanski/fast_flutter_driver#104]
Hi, Thanks for this very helpful tool. I wanted to know how to run tests if I have structured my tests by package, eg: Login, Payment etc? Is it possible to run specific folder?

**Comment by tomaszpolanski** [comment]
Hey @KrishnB ,
yes you can run specific folders or files.
Check out the example folder and there you can run `fastdriver test_driver/subdir_tests` to execute the tests only in that folder

**Comment by KrishnB** [comment]
Thank you @tomaszpolanski was able to run successfully.

**Comment by KrishnB** [comment]
@tomaszpolanski can you please suggest any reporting package that can be used with fastdriver?

**Comment by tomaszpolanski** [comment]
@KrishnB Could you elaborate what do you want to report?
Do you mean the outcome of the tests?

**Comment by KrishnB** [comment]
yes @tomaszpolanski, the outcome of tests like pass/fail/skip that can be saved as artefacts in CI?

**Comment by tomaszpolanski** [comment]
First I would like to separate mocked flutter driver tests from end-to-end flutter driver tests (that use not mocked requests).
For mocked tests, you would not need storing what tests failed as all should pass.

You would need to need storing failed tests for end-to-end.

That being clarified, check out #98 issue, there @filipproch was reporting what was the outcome of tests - you could contact him on that as in my project I use custom solution.

**Comment by KrishnB** [comment]
Thank you @tomaszpolanski will check with @filipproach. And yes, we are doing end-to-end flutter driver tests.
