### ISSUE TITLE
Use fast_flutter_driver alongside flutter driver

### ISSUE THREAD

**Issue by gronka** [tomaszpolanski/fast_flutter_driver#105]
I'd like to be able to run fast_driver and flutter driver on the same project. However, it seems as though the auto-generated fast_driver code clashes with flutter driver code. I was hoping that I could make a folder named fastdriver in the root of my project and leave existing tests in the test_driver directory. However, the two testers seem to clash in multiple ways.

Is this supported?

**Comment by tomaszpolanski** [comment]
Hey @gronka ,
`fastdriver` by default runs tests in `test_driver` but there is no problem for you to put  the tests you want to run only with `fastdriver` inside `fast_driver` folder and then just pass the tested folder/file to the tool like `fastdriver fast_driver`
