### ISSUE TITLE
unable to get tests to work

### ISSUE THREAD

**Issue by bremington** [tomaszpolanski/fast_flutter_driver#108]
Hi Tomas, I have been working many hours to get your package to work and I seem to be at a standstill.

First - I updated pubspec.yaml but was not sure from your documentation and example whether I update either dependencies with fast_flutter-driver_tool ^1.5.1 or dev_dependences with fast_flutter_driver ^1.1.0

I tried one then both and get the same result.

My app works fine running macos with no errors.

I setup three tests to run in test_driver and the test starts the generic_test.dart file...then starts my app...but then stops and provides a number of errors that don't help me in debugging where to resolve:

Here is print out of the run:

brians-mbp:master brianremington$ fastdriver
Can't load Kernel binary: Invalid kernel binary format version.
Starting tests
Testing test_driver/generic/generic_test.dart
Building application for macos...      45.3s
Syncing files...                        
Syncing files...                       0.0s
$ dart test_driver/generic/generic_test.dart -u http://127.0.0.1:65153/7HI__byYJQI=/ -r 400x700 -l en
../../flutter/.pub-cache/hosted/pub.dartlang.org/test-1.16.0-nullsafety.5/lib/test.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.9.
// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
^
../../flutter/packages/flutter/lib/material.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.9.
// Copyright 2014 The Flutter Authors. All rights reserved.
^
../../flutter/.pub-cache/hosted/pub.dartlang.org/test_core-0.3.12-nullsafety.5/lib/test_core.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.9.
// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
^
../../flutter/packages/flutter/lib/foundation.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.9.
// Copyright 2014 The Flutter Authors. All rights reserved.
^
../../flutter/packages/flutter/lib/cupertino.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.9.
// Copyright 2014 The Flutter Authors. All rights reserved.
^
../../flutter/packages/flutter/lib/services.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.9.
// Copyright 2014 The Flutter Authors. All rights reserved.
^
../../flutter/.pub-cache/hosted/pub.dartlang.org/meta-1.3.0-nullsafety.3/lib/meta.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.9.
// Copyright (c) 2016, the Dart project authors. Please see the AUTHORS file
^
../../flutter/.pub-cache/hosted/pub.dartlang.org/file-6.0.0-nullsafety.2/lib/file.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.9.
// Copyright (c) 2017, the Dart project authors.  Please see the AUTHORS file
^
../../flutter/.pub-cache/hosted/pub.dartlang.org/file-6.0.0-nullsafety.2/lib/local.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.9.
// Copyright (c) 2017, the Dart project authors.  Please see the AUTHORS file
^
../../flutter/.pub-cache/hosted/pub.dartlang.org/file-6.0.0-nullsafety.2/lib/memory.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.9.
// Copyright (c) 2017, the Dart project authors.  Please see the AUTHORS file
^
Unhandled exception:
ShellException(dart test_driver/generic/generic_test.dart -u http://127.0.0.1:65153/7HI__byYJQI=/ -r 400x700 -l en, exitCode 254, workingDirectory: /Users/brianremington/Downloads/master)
#0      Shell.runExecutableArguments (package:process_run/shell.dart:274:9)
<asynchronous suspension>
#1      Shell.run (package:process_run/shell.dart:241:33)
#2      _CommandLine.run (package:fast_flutter_driver_tool/src/preparing_tests/command_line/command_line_impl.dart:44:18)
#3      run (package:fast_flutter_driver_tool/src/preparing_tests/command_line/command_line_impl.dart:24:5)
#4      TestExecutor._runTests (package:fast_flutter_driver_tool/src/preparing_tests/testing.dart:182:16)
#5      TestExecutor.test (package:fast_flutter_driver_tool/src/preparing_tests/testing.dart:110:15)
<asynchronous suspension>
#6      run.<anonymous closure> (file:///Users/brianremington/.pub-cache/hosted/pub.dartlang.org/fast_flutter_driver_tool-1.5.1/bin/main.dart:102:41)
#7      setUp (package:fast_flutter_driver_tool/src/preparing_tests/testing.dart:31:16)
#8      run (file:///Users/brianremington/.pub-cache/hosted/pub.dartlang.org/fast_flutter_driver_tool-1.5.1/bin/main.dart:100:11)
<asynchronous suspension>
#9      main (file:///Users/brianremington/.pub-cache/hosted/pub.dartlang.org/fast_flutter_driver_tool-1.5.1/bin/main.dart:23:9)
#10     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

Here is one of the _test files:

import 'dart:convert';
import 'package:fast_flutter_driver/tool.dart';
import 'package:flutter_driver/flutter_driver.dart';
import 'package:test/test.dart';
import 'package:seed/main.dart';
import '../test_driver/generic/test_configuration.dart';

void main(List<String> args) {
  FlutterDriver driver;
  final properties = TestProperties(args);

  setUpAll(() async {
    driver = await FlutterDriver.connect(
      dartVmServiceUrl: properties.vmUrl,
    );
  });

  tearDownAll(() async {
    await driver?.close();
  });
  
  Future<void> restart() {
    db.resetApp();
    return driver.requestData(
      json.encode(
        TestConfiguration(
          resolution: properties.resolution,
          platform: properties.platform,

        ),
      ),
    );
  }

  group('all test scenarios', () {
    SerializableFinder nextIntroScreen = find.byValueKey('next');
    SerializableFinder doneIntroScreen = find.byValueKey('done');
    SerializableFinder introScreen = find.byValueKey('introStart');
    SerializableFinder assetGotIt = find.byValueKey('assetGotIt');
    SerializableFinder assetChip = find.byValueKey('assetChip');
    SerializableFinder housing = find.byValueKey('cardHousing');
    SerializableFinder savings = find.byValueKey('cardSavings');
    SerializableFinder k4011 = find.byValueKey('cardEmployer plan 1');
    SerializableFinder salary1Card = find.byValueKey('cardSalary 1');
    SerializableFinder salary1FTKeyboard = find.byValueKey('sal1FTKeyboard');
    SerializableFinder salary1Field = find.byValueKey('salary1Field');
    SerializableFinder firstHouseListTile = find.byValueKey('firstHouseListTile');
    SerializableFinder key7 = find.byValueKey('key7');
    SerializableFinder key5 = find.byValueKey('key5');
    SerializableFinder key0 = find.byValueKey('key0');
    SerializableFinder doneButtonKeyboard = find.byValueKey('doneButtonKeyboard');
    SerializableFinder doneButtonSalary = find.byValueKey('doneButtonSalary');
    SerializableFinder doneButtonSavings = find.byValueKey('doneButtonSavings');
    SerializableFinder doneButton401k = find.byValueKey('doneButton401k');
    SerializableFinder doneButtonLoanPop = find.byValueKey('doneButtonLoanPop');
    SerializableFinder doneButtonAsset = find.byValueKey('doneButtonAsset');
    SerializableFinder assetCardBackButton = find.byValueKey('assetCardBackButton');
    SerializableFinder currentHomeValueKeyboard = find.byValueKey('currentHomeValueKeyboard');
    SerializableFinder currentHomeLoanKeyboard = find.byValueKey('currentHomeLoanKeyboard');
    SerializableFinder savingsChip = find.byValueKey('savingsChip');
    SerializableFinder k401Chip = find.byValueKey('k401Chip');
    SerializableFinder savingsKeyboard = find.byValueKey('savingsKeyboard');
    SerializableFinder k401Keyboard = find.byValueKey('k401Keyboard');

    test('USAge30Single', () async {
      await driver.waitFor(introScreen);
      await driver.tap(nextIntroScreen, timeout: Duration(seconds: 1));
      await driver.tap(nextIntroScreen, timeout: Duration(seconds: 1));
      await driver.tap(nextIntroScreen, timeout: Duration(seconds: 1));
      await driver.tap(nextIntroScreen, timeout: Duration(seconds: 1));
      await driver.tap(nextIntroScreen, timeout: Duration(seconds: 1));
      await driver.tap(salary1Card, timeout: Duration(seconds: 1));
      await driver.tap(salary1FTKeyboard, timeout: Duration(seconds: 1));
      await driver.tap(key7);
      await driver.tap(key5);
      await driver.tap(key0);
      await driver.tap(key0);
      await driver.tap(key0);
      await driver.tap(doneButtonKeyboard, timeout: Duration(seconds: 2));

      // test that salary works
      await driver.waitFor(find.text("\$75,000"));
      expect(await driver.getText(salary1Field), "\$75,000");
      await driver.tap(doneButtonSalary);
      //test for social security starting at retire age
      await expectLater(db.getSalary1RetireValue(), completion(38438));
      //test for taxes complied correctly
      //taxes based on 2021 US tax tables for single living in CA
      await expectLater(db.getTaxValue(0), completion(-18423));
      //test for salary stopping at retire age for those under age 65
      await expectLater(db.getSalary1RetireValue(), completion(-100));
      //test for initial expenses estimated
      await expectLater(db.getValueByYearAndName("Food",0), completion(-7361));
      await driver.tap(doneIntroScreen, timeout: Duration(seconds: 1));
    });

    test('add savings', () async {
      await driver.tap(savings, timeout: Duration(seconds: 1));
      await driver.tap(savingsChip, timeout: Duration(seconds: 1));
      await driver.tap(savingsKeyboard, timeout: Duration(seconds: 1));
      await driver.tap(key5);
      await driver.tap(key0);
      await driver.tap(key0);
      await driver.tap(key0);
      await driver.tap(key0);
      await driver.tap(doneButtonKeyboard, timeout: Duration(seconds: 1));
      await driver.tap(doneButtonSavings);
      //test for savings at end of model
      await expectLater(db.getValueByYearAndName("Savings",39), completion(108214));
    });

    test('add 401k', () async {
      await driver.tap(k4011, timeout: Duration(seconds: 1));
      await driver.tap(k401Chip, timeout: Duration(seconds: 1));
      await driver.tap(k401Keyboard, timeout: Duration(seconds: 1));
      await driver.tap(key5);
      await driver.tap(key0);
      await driver.tap(key0);
      await driver.tap(key0);
      await driver.tap(key0);
      await driver.tap(doneButtonKeyboard, timeout: Duration(seconds: 1));
      await driver.tap(doneButton401k);
      //test for retirement account at end of model
      await expectLater(db.getValueByYearAndName("Employer plan 1",39), completion(349959));

    });

    test('add existing house', () async {
      await driver.tap(assetChip, timeout: Duration(seconds: 1));
      await driver.tap(assetGotIt, timeout: Duration(seconds: 1));
      await driver.tap(housing, timeout: Duration(seconds: 1));
      await driver.tap(firstHouseListTile, timeout: Duration(seconds: 1));
      await driver.tap(currentHomeValueKeyboard, timeout: Duration(seconds: 1));
      await driver.tap(key5);
      await driver.tap(key7);
      await driver.tap(key0);
      await driver.tap(key0);
      await driver.tap(key0);
      await driver.tap(key0);
      await driver.tap(doneButtonKeyboard, timeout: Duration(seconds: 1));
      await driver.tap(currentHomeLoanKeyboard, timeout: Duration(seconds: 1));
      await driver.tap(key5);
      await driver.tap(key5);
      await driver.tap(key0);
      await driver.tap(key0);
      await driver.tap(key0);
      await driver.tap(key0);
      await driver.tap(doneButtonKeyboard, timeout: Duration(seconds: 1));
      await driver.tap(doneButtonLoanPop);
      await driver.tap(doneButtonAsset);
      await driver.tap(assetCardBackButton);
      // check FV of home with appreciation
      await expectLater(db.getValueByYearAndName("Housing",39), completion(1233904));
      //check mortgage is being paid down..last year of payments
      await expectLater(db.getValueByYearAndName("Mortgage",29), completion(-34482));
      //check mortgage is paid off
      await expectLater(db.getValueByYearAndName("Mortgage",39), completion(0));

    });

    group('restart', () {
      test('restart', () async {
        await restart();
      });

    });

  });

  }

**Comment by tomaszpolanski** [comment]
Hey @bremington
I apologize for the late response as for some reason it did not appear in any of my notifications.
Could you tell me what Flutter version are you using?
Additionally, did you try to run the example tests on your machine as I've also tested them in nnbd code
